version: '3'
services:
  traefik-portal:
    image: lowet84/traefik-portal
    build: .
    networks:
      - homeserver2
    labels:
      - traefik.backend=traefik-portal
      - traefik.frontend.passHostHeader=true
      - traefik.port=3000
      - traefik.frontend.rule=Host:portal.fredriklowenhamn.com
    volumes:
      - /storage/Settings/portal:/data

networks:
  homeserver2:
    external: true
